name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker engine
        uses: docker/build-push-action@v4
        with:
          context: ./engine
          push: true
          tags: |
            suksham/probo_engine:latest 
            suksham/probo_engine:${{ github.sha }}

      - name: Build and push Docker ws-server
        uses: docker/build-push-action@v4
        with:
          context: ./ws
          push: true
          tags: |
            suksham/probo_ws_server:latest 
            suksham/probo_ws_server:${{ github.sha }}
          build-args: |
            - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker api-server
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: |
            suksham/probo_server:latest 
            suksham/probo_server:${{ github.sha }}

      - name: Build and push Docker db-server
        uses: docker/build-push-action@v4
        with:
          context: ./db-server
          push: true
          tags: |
            suksham/probo_db_server:latest 
            suksham/probo_db_server:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Update deployment images
        run: |
          kubectl set image deployment/server server=suksham/probo_server:${{ github.sha }}
          kubectl set image deployment/engine engine=suksham/probo_engine:${{ github.sha }}
          kubectl set image deployment/db-server db-server=suksham/probo_db_server:${{ github.sha }}
          kubectl set image deployment/ws-server ws-server=suksham/probo_ws_server:${{ github.sha }}

      - name: Verify deployment for server
        run: |
          kubectl rollout status deployment/server

      - name: Verify deployment for engine
        run: |
          kubectl rollout status deployment/engine

      - name: Verify deployment for ws-server
        run: |
          kubectl rollout status deployment/ws-server

      - name: Verify deployment for db-server
        run: |
          kubectl rollout status deployment/db-server
